# -*- coding: utf-8 -*-
"""
@Author  : yangkai
@Email   : 807440781@qq.com
@Project : KeenRobot
@Module  : __init__.py
@DateTime: 2025/1/12 19:38
"""
from .celery_config import CELERY_CONFIG
from .global_config import GLOBAL_CONFIG
from .logging_config import LOGGER
from .project_config import PROJECT_CONFIG
from .rag_config import (
    CHAT_GREETING_CANNED_REPLY,
    CHAT_SYSTEM_PROMPT_KB_EMPTY_RETRIEVAL,
    CHAT_SYSTEM_PROMPT_WITHOUT_KB,
    CHAT_SYSTEM_PROMPT_WITH_KB_CONTEXT,
    CONVERSATION_SUMMARY_MERGE_SYSTEM_PROMPT,
    HYBRID_AGENT_CHAT_SKILL_SECTION,
    HYBRID_AGENT_CORE_SYSTEM_PROMPT,
    HYBRID_AGENT_MCP_TOOLS_SECTION,
    HYBRID_AGENT_RUN_SKILL_SECTION,
    MCP_AGENT_STANDALONE_SYSTEM_PROMPT,
    resolve_chat_system_prompt,
)
from .router_registry import ROUTER_SUMMARY, ROUTER_TAGS

__all__ = (
    "CELERY_CONFIG",
    "GLOBAL_CONFIG",
    "LOGGER",
    "PROJECT_CONFIG",
    "CHAT_SYSTEM_PROMPT_WITH_KB_CONTEXT",
    "CHAT_SYSTEM_PROMPT_WITHOUT_KB",
    "CHAT_SYSTEM_PROMPT_KB_EMPTY_RETRIEVAL",
    "CHAT_GREETING_CANNED_REPLY",
    "CONVERSATION_SUMMARY_MERGE_SYSTEM_PROMPT",
    "HYBRID_AGENT_CORE_SYSTEM_PROMPT",
    "HYBRID_AGENT_CHAT_SKILL_SECTION",
    "HYBRID_AGENT_MCP_TOOLS_SECTION",
    "HYBRID_AGENT_RUN_SKILL_SECTION",
    "MCP_AGENT_STANDALONE_SYSTEM_PROMPT",
    "resolve_chat_system_prompt",
    "ROUTER_SUMMARY",
    "ROUTER_TAGS",
)
